const uint OPNop=__LINE__-1;                                //      //
const uint OPStop=__LINE__-1;                               //F     //
const uint OPAddFloatFloat=__LINE__-1;                      //F F   //F
const uint OPAddVec2Vec2=__LINE__-1;                        //V2 V2 //V2
const uint OPAddVec2Float=__LINE__-1;                       //V2 F  //V2
const uint OPAddVec3Vec3=__LINE__-1;                        //V3 V3 //V3
const uint OPAddVec3Float=__LINE__-1;                       //V3 F  //V3
const uint OPAddVec4Vec4=__LINE__-1;                        //V4 V4 //V4
const uint OPAddVec4Float=__LINE__-1;                       //V4 F  //V4
const uint OPSubFloatFloat=__LINE__-1;                      //F F   //F
const uint OPSubVec2Vec2=__LINE__-1;                        //V2 V2 //V2
const uint OPSubVec2Float=__LINE__-1;                       //V2 F  //V2
const uint OPSubVec3Vec3=__LINE__-1;                        //V3 V3 //V3
const uint OPSubVec3Float=__LINE__-1;                       //V3 F  //V3
const uint OPSubVec4Vec4=__LINE__-1;                        //V4 V4 //V4
const uint OPSubVec4Float=__LINE__-1;                       //V4 F  //V4
const uint OPMulFloatFloat=__LINE__-1;                      //F F   //F
const uint OPMulVec2Vec2=__LINE__-1;                        //V2 V2 //V2
const uint OPMulVec2Float=__LINE__-1;                       //V2 F  //V2
const uint OPMulVec3Vec3=__LINE__-1;                        //V3 V3 //V3
const uint OPMulVec3Float=__LINE__-1;                       //V3 F  //V3
const uint OPMulVec4Vec4=__LINE__-1;                        //V4 V4 //V4
const uint OPMulVec4Float=__LINE__-1;                       //V4 F  //V4
const uint OPDivFloatFloat=__LINE__-1;                      //F F   //F
const uint OPDivVec2Vec2=__LINE__-1;                        //V2 V2 //V2
const uint OPDivVec2Float=__LINE__-1;                       //V2 F  //V2
const uint OPDivVec3Vec3=__LINE__-1;                        //V3 V3 //V3
const uint OPDivVec3Float=__LINE__-1;                       //V3 F  //V3
const uint OPDivVec4Vec4=__LINE__-1;                        //V4 V4 //V4
const uint OPDivVec4Float=__LINE__-1;                       //V4 F  //V4
const uint OPModFloatFloat=__LINE__-1;                      //F F   //F
const uint OPModVec2Vec2=__LINE__-1;                        //V2 V2 //V2
const uint OPModVec2Float=__LINE__-1;                       //V2 F  //V2
const uint OPModVec3Vec3=__LINE__-1;                        //V3 V3 //V3
const uint OPModVec3Float=__LINE__-1;                       //V3 F  //V3
const uint OPModVec4Vec4=__LINE__-1;                        //V4 V4 //V4
const uint OPModVec4Float=__LINE__-1;                       //V4 F  //V4
const uint OPPowFloatFloat=__LINE__-1;                      //F F   //F
const uint OPPowVec2Vec2=__LINE__-1;                        //V2 V2 //V2
const uint OPPowVec3Vec3=__LINE__-1;                        //V3 V3 //V3
const uint OPPowVec4Vec4=__LINE__-1;                        //V4 V4 //V4
const uint OPCrossVec3=__LINE__-1;                          //V3 V3 //V3
const uint OPDotVec2=__LINE__-1;                            //V2 V2 //F
const uint OPDotVec3=__LINE__-1;                            //V3 V3 //F
const uint OPDotVec4=__LINE__-1;                            //V4 V4 //F
const uint OPLengthVec2=__LINE__-1;                         //V2    //F
const uint OPLengthVec3=__LINE__-1;                         //V3    //F
const uint OPLengthVec4=__LINE__-1;                         //V4    //F
const uint OPDistanceVec2=__LINE__-1;                       //V2 V2 //F
const uint OPDistanceVec3=__LINE__-1;                       //V3 V3 //F
const uint OPDistanceVec4=__LINE__-1;                       //V4 V4 //F
const uint OPNormalizeVec2=__LINE__-1;                      //V2    //V2
const uint OPNormalizeVec3=__LINE__-1;                      //V2    //V2
const uint OPNormalizeVec4=__LINE__-1;                      //V4    //V4
const uint OPAbsFloat=__LINE__-1;                           //F     //F
const uint OPSignFloat=__LINE__-1;                          //F     //F
const uint OPFloorFloat=__LINE__-1;                         //F     //F
const uint OPCeilFloat=__LINE__-1;                          //F     //F
const uint OPFractFloat=__LINE__-1;                         //F     //F
const uint OPSqrtFloat=__LINE__-1;                          //F     //F
const uint OPInverseSqrtFloat=__LINE__-1;                   //F     //F
const uint OPExpFloat=__LINE__-1;                           //F     //F
const uint OPExp2Float=__LINE__-1;                          //F     //F
const uint OPLogFloat=__LINE__-1;                           //F     //F
const uint OPLog2Float=__LINE__-1;                          //F     //F
const uint OPSinFloat=__LINE__-1;                           //F     //F
const uint OPCosFloat=__LINE__-1;                           //F     //F
const uint OPTanFloat=__LINE__-1;                           //F     //F
const uint OPAsinFloat=__LINE__-1;                          //F     //F
const uint OPAcosFloat=__LINE__-1;                          //F     //F
const uint OPAtanFloat=__LINE__-1;                          //F     //F
const uint OPMinFloat=__LINE__-1;                           //F F   //F
const uint OPMaxFloat=__LINE__-1;                           //F F   //F
const uint OPSmoothMinFloat=__LINE__-1;                     //F F F //F
const uint OPSmoothMaxFloat=__LINE__-1;                     //F F F //F
const uint OPMinMaterialFloat=__LINE__-1;                   //F F   //F
const uint OPMaxMaterialFloat=__LINE__-1;                   //F F   //F
const uint OPSmoothMinMaterialFloat=__LINE__-1;             //F F F //F
const uint OPSmoothMaxMaterialFloat=__LINE__-1;             //F F F //F
const uint OPDupFloat=__LINE__-1;                           //F     //F F
const uint OPDup2Float=__LINE__-1;                          //F     //F F
const uint OPDup3Float=__LINE__-1;                          //F     //F F
const uint OPDup4Float=__LINE__-1;                          //F     //F F
const uint OPAbsVec2=__LINE__-1;                            //V2    //V2
const uint OPSignVec2=__LINE__-1;                           //V2    //V2
const uint OPFloorVec2=__LINE__-1;                          //V2    //V2
const uint OPCeilVec2=__LINE__-1;                           //V2    //V2
const uint OPFractVec2=__LINE__-1;                          //V2    //V2
const uint OPSqrtVec2=__LINE__-1;                           //V2    //V2
const uint OPInverseSqrtVec2=__LINE__-1;                    //V2    //V2
const uint OPExpVec2=__LINE__-1;                            //V2    //V2
const uint OPExp2Vec2=__LINE__-1;                           //V2    //V2
const uint OPLogVec2=__LINE__-1;                            //V2    //V2
const uint OPLog2Vec2=__LINE__-1;                           //V2    //V2
const uint OPSinVec2=__LINE__-1;                            //V2    //V2
const uint OPCosVec2=__LINE__-1;                            //V2    //V2
const uint OPTanVec2=__LINE__-1;                            //V2    //V2
const uint OPAsinVec2=__LINE__-1;                           //V2    //V2
const uint OPAcosVec2=__LINE__-1;                           //V2    //V2
const uint OPAtanVec2=__LINE__-1;                           //V2    //V2
const uint OPMinVec2=__LINE__-1;                            //V2 V2 //V2
const uint OPMaxVec2=__LINE__-1;                            //V2 V2 //V2
const uint OPDupVec2=__LINE__-1;                            //V2    //V2 V2
const uint OPDup2Vec2=__LINE__-1;                           //V2    //V2 V2
const uint OPDup3Vec2=__LINE__-1;                           //V2    //V2 V2
const uint OPDup4Vec2=__LINE__-1;                           //V2    //V2 V2
const uint OPAbsVec3=__LINE__-1;                            //V3    //V3
const uint OPSignVec3=__LINE__-1;                           //V3    //V3
const uint OPFloorVec3=__LINE__-1;                          //V3    //V3
const uint OPCeilVec3=__LINE__-1;                           //V3    //V3
const uint OPFractVec3=__LINE__-1;                          //V3    //V3
const uint OPSqrtVec3=__LINE__-1;                           //V3    //V3
const uint OPInverseSqrtVec3=__LINE__-1;                    //V3    //V3
const uint OPExpVec3=__LINE__-1;                            //V3    //V3
const uint OPExp2Vec3=__LINE__-1;                           //V3    //V3
const uint OPLogVec3=__LINE__-1;                            //V3    //V3
const uint OPLog2Vec3=__LINE__-1;                           //V3    //V3
const uint OPSinVec3=__LINE__-1;                            //V3    //V3
const uint OPCosVec3=__LINE__-1;                            //V3    //V3
const uint OPTanVec3=__LINE__-1;                            //V3    //V3
const uint OPAsinVec3=__LINE__-1;                           //V3    //V3
const uint OPAcosVec3=__LINE__-1;                           //V3    //V3
const uint OPAtanVec3=__LINE__-1;                           //V3    //V3
const uint OPMinVec3=__LINE__-1;                            //V3 V3 //V3
const uint OPMaxVec3=__LINE__-1;                            //V3 V3 //V3
const uint OPDupVec3=__LINE__-1;                            //V3    //V3 V3
const uint OPDup2Vec3=__LINE__-1;                           //V3    //V3 V3
const uint OPDup3Vec3=__LINE__-1;                           //V3    //V3 V3
const uint OPDup4Vec3=__LINE__-1;                           //V3    //V3 V3
const uint OPAbsVec4=__LINE__-1;                            //V4    //V4
const uint OPSignVec4=__LINE__-1;                           //V4    //V4
const uint OPFloorVec4=__LINE__-1;                          //V4    //V4
const uint OPCeilVec4=__LINE__-1;                           //V4    //V4
const uint OPFractVec4=__LINE__-1;                          //V4    //V4
const uint OPSqrtVec4=__LINE__-1;                           //V4    //V4
const uint OPInverseSqrtVec4=__LINE__-1;                    //V4    //V4
const uint OPExpVec4=__LINE__-1;                            //V4    //V4
const uint OPExp2Vec4=__LINE__-1;                           //V4    //V4
const uint OPLogVec4=__LINE__-1;                            //V4    //V4
const uint OPLog2Vec4=__LINE__-1;                           //V4    //V4
const uint OPSinVec4=__LINE__-1;                            //V4    //V4
const uint OPCosVec4=__LINE__-1;                            //V4    //V4
const uint OPTanVec4=__LINE__-1;                            //V4    //V4
const uint OPAsinVec4=__LINE__-1;                           //V4    //V4
const uint OPAcosVec4=__LINE__-1;                           //V4    //V4
const uint OPAtanVec4=__LINE__-1;                           //V4    //V4
const uint OPMinVec4=__LINE__-1;                            //V4 V4 //V4
const uint OPMaxVec4=__LINE__-1;                            //V4 V4 //V4
const uint OPDupVec4=__LINE__-1;                            //V4    //V4 V4
const uint OPDup2Vec4=__LINE__-1;                           //V4    //V4 V4
const uint OPDup3Vec4=__LINE__-1;                           //V4    //V4 V4
const uint OPDup4Vec4=__LINE__-1;                           //V4    //V4 V4
const uint OPPromoteFloatFloatVec2=__LINE__-1;              //F F   //V2
const uint OPPromoteFloatFloatFloatVec3=__LINE__-1;         //F F F //V3
const uint OPPromoteFloatFloatFloatFloatVec4=__LINE__-1;    //F F F F //V4
const uint OPPromoteVec2FloatVec3=__LINE__-1;               //V2 F  //V3
const uint OPPromoteVec2FloatFloatVec4=__LINE__-1;          //V2 F F //V4
const uint OPPromoteVec2Vec2Vec4=__LINE__-1;                //V2 V2 //V4
const uint OPPromoteVec3FloatVec4=__LINE__-1;               //V3 F  //V4
const uint OPAcoshFloat=__LINE__-1;                         //F     //F
const uint OPAcoshVec2=__LINE__-1;                          //V2    //V2
const uint OPAcoshVec3=__LINE__-1;                          //V3    //V3
const uint OPAcoshVec4=__LINE__-1;                          //V4    //V4
const uint OPAsinhFloat=__LINE__-1;                         //F     //F
const uint OPAsinhVec2=__LINE__-1;                          //V2    //V2
const uint OPAsinhVec3=__LINE__-1;                          //V3    //V3
const uint OPAsinhVec4=__LINE__-1;                          //V4    //V4
const uint OPAtanhFloat=__LINE__-1;                         //F     //F
const uint OPAtanhVec2=__LINE__-1;                          //V2    //V2
const uint OPAtanhVec3=__LINE__-1;                          //V3    //V3
const uint OPAtanhVec4=__LINE__-1;                          //V4    //V4
const uint OPCoshFloat=__LINE__-1;                          //F     //F
const uint OPCoshVec2=__LINE__-1;                           //V2    //V2
const uint OPCoshVec3=__LINE__-1;                           //V3    //V3
const uint OPCoshVec4=__LINE__-1;                           //V4    //V4
const uint OPSinhFloat=__LINE__-1;                          //F     //F
const uint OPSinhVec2=__LINE__-1;                           //V2    //V2
const uint OPSinhVec3=__LINE__-1;                           //V3    //V3
const uint OPSinhVec4=__LINE__-1;                           //V4    //V4
const uint OPTanhFloat=__LINE__-1;                          //F     //F
const uint OPTanhVec2=__LINE__-1;                           //V2    //V2
const uint OPTanhVec3=__LINE__-1;                           //V3    //V3
const uint OPTanhVec4=__LINE__-1;                           //V4    //V4
const uint OPRoundFloat=__LINE__-1;                         //F     //F
const uint OPRoundVec2=__LINE__-1;                          //V2    //V2
const uint OPRoundVec3=__LINE__-1;                          //V3    //V3
const uint OPRoundVec4=__LINE__-1;                          //V4    //V4
const uint OPTruncFloat=__LINE__-1;                         //F     //F
const uint OPTruncVec2=__LINE__-1;                          //V2    //V2
const uint OPTruncVec3=__LINE__-1;                          //V3    //V3
const uint OPTruncVec4=__LINE__-1;                          //V4    //V4
const uint OPFMAFloat=__LINE__-1;                           //F F F //F
const uint OPFMAVec2=__LINE__-1;                            //V2 V2 V2 //V2
const uint OPFMAVec3=__LINE__-1;                            //V3 V3 V3 //V3
const uint OPFMAVec4=__LINE__-1;                            //V4 V4 V4 //V4
const uint OPClampFloatFloat=__LINE__-1;                    //F F F //F
const uint OPClampVec2Vec2=__LINE__-1;                      //V2 V2 V2 //V2
const uint OPClampVec2Float=__LINE__-1;                     //V2 F F //V2
const uint OPClampVec3Vec3=__LINE__-1;                      //V3 V3 V3 //V3
const uint OPClampVec3Float=__LINE__-1;                     //V3 F F //V3
const uint OPClampVec4Vec4=__LINE__-1;                      //V4 V4 V4 //V4
const uint OPClampVec4Float=__LINE__-1;                     //V4 F F //V4
const uint OPMixFloatFloat=__LINE__-1;                      //F F F //F
const uint OPMixVec2Vec2=__LINE__-1;                        //V2 V2 V2 //V2
const uint OPMixVec2Float=__LINE__-1;                       //V2 V2 F //V2
const uint OPMixVec3Vec3=__LINE__-1;                        //V3 V3 V3 //V3
const uint OPMixVec3Float=__LINE__-1;                       //V3 V3 F //V3
const uint OPMixVec4Vec4=__LINE__-1;                        //V4 V4 V4 //V4
const uint OPMixVec4Float=__LINE__-1;                       //V4 V4 F //V4
const uint OPSquareFloat=__LINE__-1;                        //F     //F
const uint OPCubeFloat=__LINE__-1;                          //F     //F
const uint OPSquareVec2=__LINE__-1;                         //V2    //V2
const uint OPCubeVec2=__LINE__-1;                           //V2    //V2
const uint OPSquareVec3=__LINE__-1;                         //V3    //V3
const uint OPCubeVec3=__LINE__-1;                           //V3    //V3
const uint OPSquareVec4=__LINE__-1;                         //V4    //V4
const uint OPCubeVec4=__LINE__-1;                           //V4    //V4
const uint OPSDFSphere=__LINE__-1;                          //F V3  //F
const uint OPSDFBox=__LINE__-1;                             //V3 V3 //F
const uint OPSDFTorus=__LINE__-1;                           //V2 V3 //F
const uint OPInvalid=__LINE__-1;                            //      //